// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ChessOuterMessage.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// #region Client-Realm
type C2R_Login_Req struct {
	Account  string `protobuf:"bytes,1,opt,name=Account" json:"Account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (m *C2R_Login_Req) Reset()                    { *m = C2R_Login_Req{} }
func (m *C2R_Login_Req) String() string            { return proto.CompactTextString(m) }
func (*C2R_Login_Req) ProtoMessage()               {}
func (*C2R_Login_Req) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *C2R_Login_Req) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *C2R_Login_Req) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type R2C_Login_Ack struct {
	Error   int32  `protobuf:"varint,90,opt,name=Error" json:"Error,omitempty"`
	Message string `protobuf:"bytes,91,opt,name=Message" json:"Message,omitempty"`
	Key     int64  `protobuf:"varint,1,opt,name=Key" json:"Key,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=Address" json:"Address,omitempty"`
}

func (m *R2C_Login_Ack) Reset()                    { *m = R2C_Login_Ack{} }
func (m *R2C_Login_Ack) String() string            { return proto.CompactTextString(m) }
func (*R2C_Login_Ack) ProtoMessage()               {}
func (*R2C_Login_Ack) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *R2C_Login_Ack) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *R2C_Login_Ack) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *R2C_Login_Ack) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *R2C_Login_Ack) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type C2R_Register_Req struct {
	Account  string `protobuf:"bytes,1,opt,name=Account" json:"Account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (m *C2R_Register_Req) Reset()                    { *m = C2R_Register_Req{} }
func (m *C2R_Register_Req) String() string            { return proto.CompactTextString(m) }
func (*C2R_Register_Req) ProtoMessage()               {}
func (*C2R_Register_Req) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *C2R_Register_Req) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *C2R_Register_Req) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type R2C_Register_Ack struct {
	Error   int32  `protobuf:"varint,90,opt,name=Error" json:"Error,omitempty"`
	Message string `protobuf:"bytes,91,opt,name=Message" json:"Message,omitempty"`
}

func (m *R2C_Register_Ack) Reset()                    { *m = R2C_Register_Ack{} }
func (m *R2C_Register_Ack) String() string            { return proto.CompactTextString(m) }
func (*R2C_Register_Ack) ProtoMessage()               {}
func (*R2C_Register_Ack) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *R2C_Register_Ack) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *R2C_Register_Ack) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// #endregion
// #region Client-Gate
type C2G_LoginGate_Req struct {
	Key int64 `protobuf:"varint,1,opt,name=Key" json:"Key,omitempty"`
}

func (m *C2G_LoginGate_Req) Reset()                    { *m = C2G_LoginGate_Req{} }
func (m *C2G_LoginGate_Req) String() string            { return proto.CompactTextString(m) }
func (*C2G_LoginGate_Req) ProtoMessage()               {}
func (*C2G_LoginGate_Req) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *C2G_LoginGate_Req) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

type G2C_LoginGate_Ack struct {
	Error    int32  `protobuf:"varint,90,opt,name=Error" json:"Error,omitempty"`
	Message  string `protobuf:"bytes,91,opt,name=Message" json:"Message,omitempty"`
	PlayerID int64  `protobuf:"varint,1,opt,name=PlayerID" json:"PlayerID,omitempty"`
	UserID   int64  `protobuf:"varint,2,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *G2C_LoginGate_Ack) Reset()                    { *m = G2C_LoginGate_Ack{} }
func (m *G2C_LoginGate_Ack) String() string            { return proto.CompactTextString(m) }
func (*G2C_LoginGate_Ack) ProtoMessage()               {}
func (*G2C_LoginGate_Ack) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *G2C_LoginGate_Ack) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *G2C_LoginGate_Ack) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *G2C_LoginGate_Ack) GetPlayerID() int64 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *G2C_LoginGate_Ack) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type C2G_GetUserInfo_Req struct {
	UserID int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *C2G_GetUserInfo_Req) Reset()                    { *m = C2G_GetUserInfo_Req{} }
func (m *C2G_GetUserInfo_Req) String() string            { return proto.CompactTextString(m) }
func (*C2G_GetUserInfo_Req) ProtoMessage()               {}
func (*C2G_GetUserInfo_Req) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *C2G_GetUserInfo_Req) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type G2C_GetUserInfo_Ack struct {
	Error    int32  `protobuf:"varint,90,opt,name=Error" json:"Error,omitempty"`
	Message  string `protobuf:"bytes,91,opt,name=Message" json:"Message,omitempty"`
	NickName string `protobuf:"bytes,1,opt,name=NickName" json:"NickName,omitempty"`
	Money    int64  `protobuf:"varint,4,opt,name=Money" json:"Money,omitempty"`
}

func (m *G2C_GetUserInfo_Ack) Reset()                    { *m = G2C_GetUserInfo_Ack{} }
func (m *G2C_GetUserInfo_Ack) String() string            { return proto.CompactTextString(m) }
func (*G2C_GetUserInfo_Ack) ProtoMessage()               {}
func (*G2C_GetUserInfo_Ack) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *G2C_GetUserInfo_Ack) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *G2C_GetUserInfo_Ack) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *G2C_GetUserInfo_Ack) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *G2C_GetUserInfo_Ack) GetMoney() int64 {
	if m != nil {
		return m.Money
	}
	return 0
}

type C2G_StartMatch_Req struct {
}

func (m *C2G_StartMatch_Req) Reset()                    { *m = C2G_StartMatch_Req{} }
func (m *C2G_StartMatch_Req) String() string            { return proto.CompactTextString(m) }
func (*C2G_StartMatch_Req) ProtoMessage()               {}
func (*C2G_StartMatch_Req) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

type G2C_StartMatch_Ack struct {
	Error   int32  `protobuf:"varint,90,opt,name=Error" json:"Error,omitempty"`
	Message string `protobuf:"bytes,91,opt,name=Message" json:"Message,omitempty"`
}

func (m *G2C_StartMatch_Ack) Reset()                    { *m = G2C_StartMatch_Ack{} }
func (m *G2C_StartMatch_Ack) String() string            { return proto.CompactTextString(m) }
func (*G2C_StartMatch_Ack) ProtoMessage()               {}
func (*G2C_StartMatch_Ack) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *G2C_StartMatch_Ack) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *G2C_StartMatch_Ack) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type C2G_ReturnLobby_Ntt struct {
}

func (m *C2G_ReturnLobby_Ntt) Reset()                    { *m = C2G_ReturnLobby_Ntt{} }
func (m *C2G_ReturnLobby_Ntt) String() string            { return proto.CompactTextString(m) }
func (*C2G_ReturnLobby_Ntt) ProtoMessage()               {}
func (*C2G_ReturnLobby_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

type C2G_CreateRoom_Req struct {
	Error   int32  `protobuf:"varint,90,opt,name=Error" json:"Error,omitempty"`
	Message string `protobuf:"bytes,91,opt,name=Message" json:"Message,omitempty"`
	UserID  int64  `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *C2G_CreateRoom_Req) Reset()                    { *m = C2G_CreateRoom_Req{} }
func (m *C2G_CreateRoom_Req) String() string            { return proto.CompactTextString(m) }
func (*C2G_CreateRoom_Req) ProtoMessage()               {}
func (*C2G_CreateRoom_Req) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *C2G_CreateRoom_Req) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *C2G_CreateRoom_Req) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *C2G_CreateRoom_Req) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type G2C_CreateRoom_Ack struct {
}

func (m *G2C_CreateRoom_Ack) Reset()                    { *m = G2C_CreateRoom_Ack{} }
func (m *G2C_CreateRoom_Ack) String() string            { return proto.CompactTextString(m) }
func (*G2C_CreateRoom_Ack) ProtoMessage()               {}
func (*G2C_CreateRoom_Ack) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

// #endregion
// #region Gate-Client
type G2C_PlayerDisconnect_Ntt struct {
}

func (m *G2C_PlayerDisconnect_Ntt) Reset()                    { *m = G2C_PlayerDisconnect_Ntt{} }
func (m *G2C_PlayerDisconnect_Ntt) String() string            { return proto.CompactTextString(m) }
func (*G2C_PlayerDisconnect_Ntt) ProtoMessage()               {}
func (*G2C_PlayerDisconnect_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

// #endregion
// #region g-Center
// #endregion Center-Client
// #region Client-Map
type Actor_GamerReady_Ntt struct {
	UserID int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *Actor_GamerReady_Ntt) Reset()                    { *m = Actor_GamerReady_Ntt{} }
func (m *Actor_GamerReady_Ntt) String() string            { return proto.CompactTextString(m) }
func (*Actor_GamerReady_Ntt) ProtoMessage()               {}
func (*Actor_GamerReady_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *Actor_GamerReady_Ntt) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type Actor_GamerGrabLandlordSelect_Ntt struct {
	UserID int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	IsGrab bool  `protobuf:"varint,2,opt,name=IsGrab" json:"IsGrab,omitempty"`
}

func (m *Actor_GamerGrabLandlordSelect_Ntt) Reset()         { *m = Actor_GamerGrabLandlordSelect_Ntt{} }
func (m *Actor_GamerGrabLandlordSelect_Ntt) String() string { return proto.CompactTextString(m) }
func (*Actor_GamerGrabLandlordSelect_Ntt) ProtoMessage()    {}
func (*Actor_GamerGrabLandlordSelect_Ntt) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{15}
}

func (m *Actor_GamerGrabLandlordSelect_Ntt) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Actor_GamerGrabLandlordSelect_Ntt) GetIsGrab() bool {
	if m != nil {
		return m.IsGrab
	}
	return false
}

type Actor_GamerPlayCard_Req struct {
	Cards []*CCard `protobuf:"bytes,1,rep,name=Cards" json:"Cards,omitempty"`
}

func (m *Actor_GamerPlayCard_Req) Reset()                    { *m = Actor_GamerPlayCard_Req{} }
func (m *Actor_GamerPlayCard_Req) String() string            { return proto.CompactTextString(m) }
func (*Actor_GamerPlayCard_Req) ProtoMessage()               {}
func (*Actor_GamerPlayCard_Req) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *Actor_GamerPlayCard_Req) GetCards() []*CCard {
	if m != nil {
		return m.Cards
	}
	return nil
}

type Actor_GamerPlayCard_Ack struct {
	Error   int32  `protobuf:"varint,90,opt,name=Error" json:"Error,omitempty"`
	Message string `protobuf:"bytes,91,opt,name=Message" json:"Message,omitempty"`
}

func (m *Actor_GamerPlayCard_Ack) Reset()                    { *m = Actor_GamerPlayCard_Ack{} }
func (m *Actor_GamerPlayCard_Ack) String() string            { return proto.CompactTextString(m) }
func (*Actor_GamerPlayCard_Ack) ProtoMessage()               {}
func (*Actor_GamerPlayCard_Ack) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *Actor_GamerPlayCard_Ack) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *Actor_GamerPlayCard_Ack) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Actor_GamerPlayCard_Ntt struct {
	UserID int64    `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	Cards  []*CCard `protobuf:"bytes,2,rep,name=Cards" json:"Cards,omitempty"`
}

func (m *Actor_GamerPlayCard_Ntt) Reset()                    { *m = Actor_GamerPlayCard_Ntt{} }
func (m *Actor_GamerPlayCard_Ntt) String() string            { return proto.CompactTextString(m) }
func (*Actor_GamerPlayCard_Ntt) ProtoMessage()               {}
func (*Actor_GamerPlayCard_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *Actor_GamerPlayCard_Ntt) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Actor_GamerPlayCard_Ntt) GetCards() []*CCard {
	if m != nil {
		return m.Cards
	}
	return nil
}

type Actor_GamerPrompt_Req struct {
}

func (m *Actor_GamerPrompt_Req) Reset()                    { *m = Actor_GamerPrompt_Req{} }
func (m *Actor_GamerPrompt_Req) String() string            { return proto.CompactTextString(m) }
func (*Actor_GamerPrompt_Req) ProtoMessage()               {}
func (*Actor_GamerPrompt_Req) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

type Actor_GamerPrompt_Ack struct {
	Error   int32    `protobuf:"varint,90,opt,name=Error" json:"Error,omitempty"`
	Message string   `protobuf:"bytes,91,opt,name=Message" json:"Message,omitempty"`
	Cards   []*CCard `protobuf:"bytes,1,rep,name=Cards" json:"Cards,omitempty"`
}

func (m *Actor_GamerPrompt_Ack) Reset()                    { *m = Actor_GamerPrompt_Ack{} }
func (m *Actor_GamerPrompt_Ack) String() string            { return proto.CompactTextString(m) }
func (*Actor_GamerPrompt_Ack) ProtoMessage()               {}
func (*Actor_GamerPrompt_Ack) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *Actor_GamerPrompt_Ack) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *Actor_GamerPrompt_Ack) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Actor_GamerPrompt_Ack) GetCards() []*CCard {
	if m != nil {
		return m.Cards
	}
	return nil
}

type Actor_GamerDontPlay_Ntt struct {
	UserID int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *Actor_GamerDontPlay_Ntt) Reset()                    { *m = Actor_GamerDontPlay_Ntt{} }
func (m *Actor_GamerDontPlay_Ntt) String() string            { return proto.CompactTextString(m) }
func (*Actor_GamerDontPlay_Ntt) ProtoMessage()               {}
func (*Actor_GamerDontPlay_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *Actor_GamerDontPlay_Ntt) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type Actor_Trusteeship_Ntt struct {
	UserID        int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	IsTrusteeship bool  `protobuf:"varint,2,opt,name=isTrusteeship" json:"isTrusteeship,omitempty"`
}

func (m *Actor_Trusteeship_Ntt) Reset()                    { *m = Actor_Trusteeship_Ntt{} }
func (m *Actor_Trusteeship_Ntt) String() string            { return proto.CompactTextString(m) }
func (*Actor_Trusteeship_Ntt) ProtoMessage()               {}
func (*Actor_Trusteeship_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *Actor_Trusteeship_Ntt) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Actor_Trusteeship_Ntt) GetIsTrusteeship() bool {
	if m != nil {
		return m.IsTrusteeship
	}
	return false
}

// #endregion
// #region Map-Client
type CGamerInfo struct {
	UserID    int64  `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	NickName  string `protobuf:"bytes,2,opt,name=NickName" json:"NickName,omitempty"`
	Money     int64  `protobuf:"varint,3,opt,name=Money" json:"Money,omitempty"`
	SeatID    int32  `protobuf:"varint,10,opt,name=SeatID" json:"SeatID,omitempty"`
	IsReady   bool   `protobuf:"varint,11,opt,name=IsReady" json:"IsReady,omitempty"`
	IsOffline bool   `protobuf:"varint,12,opt,name=IsOffline" json:"IsOffline,omitempty"`
}

func (m *CGamerInfo) Reset()                    { *m = CGamerInfo{} }
func (m *CGamerInfo) String() string            { return proto.CompactTextString(m) }
func (*CGamerInfo) ProtoMessage()               {}
func (*CGamerInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

func (m *CGamerInfo) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CGamerInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *CGamerInfo) GetMoney() int64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *CGamerInfo) GetSeatID() int32 {
	if m != nil {
		return m.SeatID
	}
	return 0
}

func (m *CGamerInfo) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

func (m *CGamerInfo) GetIsOffline() bool {
	if m != nil {
		return m.IsOffline
	}
	return false
}

type CGamerCards struct {
	GamerCards []*CCard `protobuf:"bytes,1,rep,name=GamerCards" json:"GamerCards,omitempty"`
}

func (m *CGamerCards) Reset()                    { *m = CGamerCards{} }
func (m *CGamerCards) String() string            { return proto.CompactTextString(m) }
func (*CGamerCards) ProtoMessage()               {}
func (*CGamerCards) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

func (m *CGamerCards) GetGamerCards() []*CCard {
	if m != nil {
		return m.GamerCards
	}
	return nil
}

type Actor_GamerEnterRoom_Ntt struct {
	Gamer *CGamerInfo `protobuf:"bytes,1,opt,name=Gamer" json:"Gamer,omitempty"`
}

func (m *Actor_GamerEnterRoom_Ntt) Reset()                    { *m = Actor_GamerEnterRoom_Ntt{} }
func (m *Actor_GamerEnterRoom_Ntt) String() string            { return proto.CompactTextString(m) }
func (*Actor_GamerEnterRoom_Ntt) ProtoMessage()               {}
func (*Actor_GamerEnterRoom_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

func (m *Actor_GamerEnterRoom_Ntt) GetGamer() *CGamerInfo {
	if m != nil {
		return m.Gamer
	}
	return nil
}

type Actor_GamersInRoom_Ntt struct {
	Gamers []*CGamerInfo `protobuf:"bytes,3,rep,name=Gamers" json:"Gamers,omitempty"`
}

func (m *Actor_GamersInRoom_Ntt) Reset()                    { *m = Actor_GamersInRoom_Ntt{} }
func (m *Actor_GamersInRoom_Ntt) String() string            { return proto.CompactTextString(m) }
func (*Actor_GamersInRoom_Ntt) ProtoMessage()               {}
func (*Actor_GamersInRoom_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

func (m *Actor_GamersInRoom_Ntt) GetGamers() []*CGamerInfo {
	if m != nil {
		return m.Gamers
	}
	return nil
}

type Actor_GamerExitRoom_Ntt struct {
	UserID int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *Actor_GamerExitRoom_Ntt) Reset()                    { *m = Actor_GamerExitRoom_Ntt{} }
func (m *Actor_GamerExitRoom_Ntt) String() string            { return proto.CompactTextString(m) }
func (*Actor_GamerExitRoom_Ntt) ProtoMessage()               {}
func (*Actor_GamerExitRoom_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

func (m *Actor_GamerExitRoom_Ntt) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type Actor_GamerReconnect_Ntt struct {
	Multiples              int32          `protobuf:"varint,1,opt,name=Multiples" json:"Multiples,omitempty"`
	LordCards              []*CCard       `protobuf:"bytes,2,rep,name=LordCards" json:"LordCards,omitempty"`
	GamersIdentity         []CIdentity    `protobuf:"varint,10,rep,packed,name=GamersIdentity,enum=msg.CIdentity" json:"GamersIdentity,omitempty"`
	DesksCards             []*CGamerCards `protobuf:"bytes,11,rep,name=DesksCards" json:"DesksCards,omitempty"`
	GamerGrabLandlordState []bool         `protobuf:"varint,12,rep,packed,name=GamerGrabLandlordState" json:"GamerGrabLandlordState,omitempty"`
}

func (m *Actor_GamerReconnect_Ntt) Reset()                    { *m = Actor_GamerReconnect_Ntt{} }
func (m *Actor_GamerReconnect_Ntt) String() string            { return proto.CompactTextString(m) }
func (*Actor_GamerReconnect_Ntt) ProtoMessage()               {}
func (*Actor_GamerReconnect_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{28} }

func (m *Actor_GamerReconnect_Ntt) GetMultiples() int32 {
	if m != nil {
		return m.Multiples
	}
	return 0
}

func (m *Actor_GamerReconnect_Ntt) GetLordCards() []*CCard {
	if m != nil {
		return m.LordCards
	}
	return nil
}

func (m *Actor_GamerReconnect_Ntt) GetGamersIdentity() []CIdentity {
	if m != nil {
		return m.GamersIdentity
	}
	return nil
}

func (m *Actor_GamerReconnect_Ntt) GetDesksCards() []*CGamerCards {
	if m != nil {
		return m.DesksCards
	}
	return nil
}

func (m *Actor_GamerReconnect_Ntt) GetGamerGrabLandlordState() []bool {
	if m != nil {
		return m.GamerGrabLandlordState
	}
	return nil
}

type Actor_GameStart_Ntt struct {
	GamersUserID     []int64        `protobuf:"varint,1,rep,packed,name=GamersUserID" json:"GamersUserID,omitempty"`
	GamersCardsCount []int32        `protobuf:"varint,3,rep,packed,name=GamersCardsCount" json:"GamersCardsCount,omitempty"`
	GamersCards      []*CGamerCards `protobuf:"bytes,2,rep,name=GamersCards" json:"GamersCards,omitempty"`
}

func (m *Actor_GameStart_Ntt) Reset()                    { *m = Actor_GameStart_Ntt{} }
func (m *Actor_GameStart_Ntt) String() string            { return proto.CompactTextString(m) }
func (*Actor_GameStart_Ntt) ProtoMessage()               {}
func (*Actor_GameStart_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{29} }

func (m *Actor_GameStart_Ntt) GetGamersUserID() []int64 {
	if m != nil {
		return m.GamersUserID
	}
	return nil
}

func (m *Actor_GameStart_Ntt) GetGamersCardsCount() []int32 {
	if m != nil {
		return m.GamersCardsCount
	}
	return nil
}

func (m *Actor_GameStart_Ntt) GetGamersCards() []*CGamerCards {
	if m != nil {
		return m.GamersCards
	}
	return nil
}

type Actor_AuthorityGrabLandlord_Ntt struct {
	UserID int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *Actor_AuthorityGrabLandlord_Ntt) Reset()         { *m = Actor_AuthorityGrabLandlord_Ntt{} }
func (m *Actor_AuthorityGrabLandlord_Ntt) String() string { return proto.CompactTextString(m) }
func (*Actor_AuthorityGrabLandlord_Ntt) ProtoMessage()    {}
func (*Actor_AuthorityGrabLandlord_Ntt) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{30}
}

func (m *Actor_AuthorityGrabLandlord_Ntt) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type Actor_AuthorityPlayCard_Ntt struct {
	UserID  int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	IsFirst bool  `protobuf:"varint,2,opt,name=IsFirst" json:"IsFirst,omitempty"`
}

func (m *Actor_AuthorityPlayCard_Ntt) Reset()                    { *m = Actor_AuthorityPlayCard_Ntt{} }
func (m *Actor_AuthorityPlayCard_Ntt) String() string            { return proto.CompactTextString(m) }
func (*Actor_AuthorityPlayCard_Ntt) ProtoMessage()               {}
func (*Actor_AuthorityPlayCard_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{31} }

func (m *Actor_AuthorityPlayCard_Ntt) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Actor_AuthorityPlayCard_Ntt) GetIsFirst() bool {
	if m != nil {
		return m.IsFirst
	}
	return false
}

type Actor_SetMultiples_Ntt struct {
	Multiples int32 `protobuf:"varint,1,opt,name=Multiples" json:"Multiples,omitempty"`
}

func (m *Actor_SetMultiples_Ntt) Reset()                    { *m = Actor_SetMultiples_Ntt{} }
func (m *Actor_SetMultiples_Ntt) String() string            { return proto.CompactTextString(m) }
func (*Actor_SetMultiples_Ntt) ProtoMessage()               {}
func (*Actor_SetMultiples_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{32} }

func (m *Actor_SetMultiples_Ntt) GetMultiples() int32 {
	if m != nil {
		return m.Multiples
	}
	return 0
}

type Actor_SetLandlord_Ntt struct {
	UserID    int64    `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	LordCards []*CCard `protobuf:"bytes,2,rep,name=LordCards" json:"LordCards,omitempty"`
}

func (m *Actor_SetLandlord_Ntt) Reset()                    { *m = Actor_SetLandlord_Ntt{} }
func (m *Actor_SetLandlord_Ntt) String() string            { return proto.CompactTextString(m) }
func (*Actor_SetLandlord_Ntt) ProtoMessage()               {}
func (*Actor_SetLandlord_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{33} }

func (m *Actor_SetLandlord_Ntt) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Actor_SetLandlord_Ntt) GetLordCards() []*CCard {
	if m != nil {
		return m.LordCards
	}
	return nil
}

type Actor_Gameover_Ntt struct {
	Winner            CIdentity `protobuf:"varint,1,opt,name=Winner,enum=msg.CIdentity" json:"Winner,omitempty"`
	BasePointPerMatch int64     `protobuf:"varint,2,opt,name=BasePointPerMatch" json:"BasePointPerMatch,omitempty"`
	Multiples         int32     `protobuf:"varint,3,opt,name=Multiples" json:"Multiples,omitempty"`
}

func (m *Actor_Gameover_Ntt) Reset()                    { *m = Actor_Gameover_Ntt{} }
func (m *Actor_Gameover_Ntt) String() string            { return proto.CompactTextString(m) }
func (*Actor_Gameover_Ntt) ProtoMessage()               {}
func (*Actor_Gameover_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{34} }

func (m *Actor_Gameover_Ntt) GetWinner() CIdentity {
	if m != nil {
		return m.Winner
	}
	return CIdentity_CIdentity_NULL
}

func (m *Actor_Gameover_Ntt) GetBasePointPerMatch() int64 {
	if m != nil {
		return m.BasePointPerMatch
	}
	return 0
}

func (m *Actor_Gameover_Ntt) GetMultiples() int32 {
	if m != nil {
		return m.Multiples
	}
	return 0
}

type Actor_GamerMoneyLess_Ntt struct {
	UserID int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *Actor_GamerMoneyLess_Ntt) Reset()                    { *m = Actor_GamerMoneyLess_Ntt{} }
func (m *Actor_GamerMoneyLess_Ntt) String() string            { return proto.CompactTextString(m) }
func (*Actor_GamerMoneyLess_Ntt) ProtoMessage()               {}
func (*Actor_GamerMoneyLess_Ntt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{35} }

func (m *Actor_GamerMoneyLess_Ntt) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func init() {
	proto.RegisterType((*C2R_Login_Req)(nil), "msg.C2R_Login_Req")
	proto.RegisterType((*R2C_Login_Ack)(nil), "msg.R2C_Login_Ack")
	proto.RegisterType((*C2R_Register_Req)(nil), "msg.C2R_Register_Req")
	proto.RegisterType((*R2C_Register_Ack)(nil), "msg.R2C_Register_Ack")
	proto.RegisterType((*C2G_LoginGate_Req)(nil), "msg.C2G_LoginGate_Req")
	proto.RegisterType((*G2C_LoginGate_Ack)(nil), "msg.G2C_LoginGate_Ack")
	proto.RegisterType((*C2G_GetUserInfo_Req)(nil), "msg.C2G_GetUserInfo_Req")
	proto.RegisterType((*G2C_GetUserInfo_Ack)(nil), "msg.G2C_GetUserInfo_Ack")
	proto.RegisterType((*C2G_StartMatch_Req)(nil), "msg.C2G_StartMatch_Req")
	proto.RegisterType((*G2C_StartMatch_Ack)(nil), "msg.G2C_StartMatch_Ack")
	proto.RegisterType((*C2G_ReturnLobby_Ntt)(nil), "msg.C2G_ReturnLobby_Ntt")
	proto.RegisterType((*C2G_CreateRoom_Req)(nil), "msg.C2G_CreateRoom_Req")
	proto.RegisterType((*G2C_CreateRoom_Ack)(nil), "msg.G2C_CreateRoom_Ack")
	proto.RegisterType((*G2C_PlayerDisconnect_Ntt)(nil), "msg.G2C_PlayerDisconnect_Ntt")
	proto.RegisterType((*Actor_GamerReady_Ntt)(nil), "msg.Actor_GamerReady_Ntt")
	proto.RegisterType((*Actor_GamerGrabLandlordSelect_Ntt)(nil), "msg.Actor_GamerGrabLandlordSelect_Ntt")
	proto.RegisterType((*Actor_GamerPlayCard_Req)(nil), "msg.Actor_GamerPlayCard_Req")
	proto.RegisterType((*Actor_GamerPlayCard_Ack)(nil), "msg.Actor_GamerPlayCard_Ack")
	proto.RegisterType((*Actor_GamerPlayCard_Ntt)(nil), "msg.Actor_GamerPlayCard_Ntt")
	proto.RegisterType((*Actor_GamerPrompt_Req)(nil), "msg.Actor_GamerPrompt_Req")
	proto.RegisterType((*Actor_GamerPrompt_Ack)(nil), "msg.Actor_GamerPrompt_Ack")
	proto.RegisterType((*Actor_GamerDontPlay_Ntt)(nil), "msg.Actor_GamerDontPlay_Ntt")
	proto.RegisterType((*Actor_Trusteeship_Ntt)(nil), "msg.Actor_Trusteeship_Ntt")
	proto.RegisterType((*CGamerInfo)(nil), "msg.CGamerInfo")
	proto.RegisterType((*CGamerCards)(nil), "msg.CGamerCards")
	proto.RegisterType((*Actor_GamerEnterRoom_Ntt)(nil), "msg.Actor_GamerEnterRoom_Ntt")
	proto.RegisterType((*Actor_GamersInRoom_Ntt)(nil), "msg.Actor_GamersInRoom_Ntt")
	proto.RegisterType((*Actor_GamerExitRoom_Ntt)(nil), "msg.Actor_GamerExitRoom_Ntt")
	proto.RegisterType((*Actor_GamerReconnect_Ntt)(nil), "msg.Actor_GamerReconnect_Ntt")
	proto.RegisterType((*Actor_GameStart_Ntt)(nil), "msg.Actor_GameStart_Ntt")
	proto.RegisterType((*Actor_AuthorityGrabLandlord_Ntt)(nil), "msg.Actor_AuthorityGrabLandlord_Ntt")
	proto.RegisterType((*Actor_AuthorityPlayCard_Ntt)(nil), "msg.Actor_AuthorityPlayCard_Ntt")
	proto.RegisterType((*Actor_SetMultiples_Ntt)(nil), "msg.Actor_SetMultiples_Ntt")
	proto.RegisterType((*Actor_SetLandlord_Ntt)(nil), "msg.Actor_SetLandlord_Ntt")
	proto.RegisterType((*Actor_Gameover_Ntt)(nil), "msg.Actor_Gameover_Ntt")
	proto.RegisterType((*Actor_GamerMoneyLess_Ntt)(nil), "msg.Actor_GamerMoneyLess_Ntt")
}

func init() { proto.RegisterFile("ChessOuterMessage.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 949 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x6d, 0x6f, 0x2a, 0x45,
	0x14, 0x0e, 0x5d, 0xa9, 0xed, 0xe1, 0xb6, 0xd2, 0x6d, 0x6f, 0xbb, 0xa9, 0x26, 0xe2, 0xc4, 0xab,
	0xe4, 0x46, 0x1b, 0xc5, 0xa4, 0xc9, 0x8d, 0x9f, 0xb8, 0x50, 0x91, 0x08, 0x6d, 0x33, 0x78, 0x63,
	0x7c, 0x49, 0x9a, 0x2d, 0x7b, 0x4a, 0x37, 0xc0, 0x4e, 0x9d, 0x19, 0xac, 0x7c, 0xf7, 0x83, 0x7f,
	0xc1, 0x3f, 0xe0, 0xef, 0x34, 0x73, 0x66, 0x59, 0x86, 0xd2, 0xe5, 0x56, 0xee, 0x37, 0xce, 0xcb,
	0x3c, 0xf3, 0x9c, 0xe7, 0x9c, 0x33, 0x2c, 0x1c, 0x35, 0x6e, 0x51, 0xa9, 0x8b, 0x89, 0x46, 0xd9,
	0x45, 0xa5, 0xc2, 0x01, 0x9e, 0xdc, 0x49, 0xa1, 0x85, 0xef, 0x8d, 0xd5, 0xe0, 0xb8, 0x4c, 0xd1,
	0xae, 0x88, 0x70, 0x64, 0xdd, 0xec, 0x0c, 0x76, 0x1a, 0x35, 0x7e, 0xd5, 0x11, 0x83, 0x38, 0xb9,
	0xe2, 0xf8, 0xbb, 0x1f, 0xc0, 0xfb, 0xf5, 0x7e, 0x5f, 0x4c, 0x12, 0x1d, 0x14, 0x2a, 0x85, 0xea,
	0x36, 0x9f, 0x99, 0xfe, 0x31, 0x6c, 0x5d, 0x86, 0x4a, 0xdd, 0x0b, 0x19, 0x05, 0x1b, 0x14, 0xca,
	0x6c, 0x36, 0x84, 0x1d, 0x5e, 0x6b, 0xa4, 0x30, 0xf5, 0xfe, 0xd0, 0x3f, 0x80, 0xe2, 0x99, 0x94,
	0x42, 0x06, 0xbf, 0x54, 0x0a, 0xd5, 0x22, 0xb7, 0x86, 0x01, 0x4f, 0x59, 0x05, 0xbf, 0x5a, 0xf0,
	0xd4, 0xf4, 0xcb, 0xe0, 0xfd, 0x80, 0x53, 0xba, 0xd2, 0xe3, 0xe6, 0x27, 0x11, 0x89, 0x22, 0x89,
	0x4a, 0xa5, 0xb7, 0xcd, 0x4c, 0xf6, 0x3d, 0x94, 0x0d, 0x67, 0x8e, 0x83, 0x58, 0x69, 0x94, 0xef,
	0x40, 0xfb, 0x35, 0x94, 0x0d, 0xed, 0x0c, 0x69, 0x0d, 0xe6, 0xec, 0x05, 0xec, 0x35, 0x6a, 0x2d,
	0x5b, 0x7a, 0x2b, 0xd4, 0x48, 0x74, 0x96, 0xca, 0x61, 0xf7, 0xb0, 0xd7, 0x9a, 0x29, 0x44, 0x69,
	0xeb, 0xa8, 0x64, 0x6a, 0x19, 0x85, 0x53, 0x94, 0xed, 0x66, 0x8a, 0x9d, 0xd9, 0xfe, 0x21, 0x6c,
	0xbe, 0x51, 0x14, 0xd9, 0xa0, 0x48, 0x6a, 0xb1, 0x2f, 0x61, 0xdf, 0xf0, 0x6b, 0xa1, 0x26, 0x47,
	0x72, 0x23, 0x88, 0xe1, 0x3c, 0xbd, 0xb0, 0x90, 0x7e, 0x0f, 0xfb, 0x86, 0xa7, 0x9b, 0xbe, 0x26,
	0xd3, 0xf3, 0xb8, 0x3f, 0x3c, 0x0f, 0xc7, 0x98, 0x36, 0x24, 0xb3, 0x0d, 0x56, 0x57, 0x24, 0x38,
	0x0d, 0xde, 0xa3, 0x9b, 0xad, 0xc1, 0x0e, 0xc0, 0x37, 0x3c, 0x7b, 0x3a, 0x94, 0xba, 0x1b, 0xea,
	0xfe, 0xad, 0xa1, 0xc9, 0x9a, 0xe0, 0x1b, 0x3a, 0x8e, 0x77, 0x9d, 0x1e, 0x3d, 0xb7, 0x1a, 0x70,
	0xd4, 0x13, 0x99, 0x74, 0xc4, 0xf5, 0xf5, 0xf4, 0xea, 0x5c, 0x6b, 0xf6, 0x9b, 0xbd, 0xb2, 0x21,
	0x31, 0xd4, 0xc8, 0x85, 0x18, 0x93, 0x32, 0xff, 0xb7, 0xd4, 0x3c, 0x25, 0x0f, 0x2c, 0x75, 0x07,
	0xbd, 0xde, 0x1f, 0xb2, 0x63, 0x08, 0x8c, 0xd7, 0xb6, 0xad, 0x19, 0xab, 0xbe, 0x48, 0x12, 0xec,
	0x6b, 0xe2, 0x73, 0x02, 0x07, 0xf5, 0xbe, 0x16, 0xf2, 0xaa, 0x15, 0x8e, 0x51, 0x72, 0x0c, 0x23,
	0xe2, 0x99, 0x7b, 0x43, 0x0f, 0x3e, 0x71, 0xf2, 0x5b, 0x32, 0xbc, 0xee, 0x84, 0x49, 0x34, 0x12,
	0x32, 0xea, 0xe1, 0x28, 0x05, 0xcd, 0x3b, 0x6c, 0xfc, 0x6d, 0x65, 0xce, 0xd0, 0xbc, 0x6c, 0xf1,
	0xd4, 0x62, 0xdf, 0xc2, 0x91, 0x03, 0x6a, 0x78, 0x36, 0x42, 0x19, 0x91, 0x32, 0x15, 0x28, 0x9a,
	0xdf, 0x2a, 0x28, 0x54, 0xbc, 0x6a, 0xa9, 0x06, 0x27, 0x63, 0x35, 0x38, 0x69, 0x18, 0x17, 0xb7,
	0x01, 0xd6, 0x7e, 0xfc, 0xf0, 0x3a, 0x3d, 0xeb, 0x3d, 0x0e, 0xb5, 0xaa, 0xa4, 0x8c, 0xdf, 0x46,
	0x1e, 0xbf, 0x23, 0x78, 0xee, 0x82, 0x4a, 0x31, 0xbe, 0xd3, 0x34, 0x67, 0xf1, 0x63, 0x81, 0x75,
	0x06, 0xff, 0xed, 0x1a, 0x7d, 0xbd, 0x50, 0x58, 0x53, 0x24, 0xda, 0x14, 0xb7, 0xb2, 0xd1, 0x6f,
	0x66, 0xec, 0x7e, 0x94, 0x13, 0xa5, 0x11, 0xd5, 0x6d, 0x7c, 0xb7, 0x52, 0x89, 0x4f, 0x61, 0x27,
	0x56, 0x4e, 0x72, 0xda, 0xe3, 0x45, 0x27, 0xfb, 0xb7, 0x00, 0xd0, 0x20, 0x16, 0x66, 0xcf, 0x73,
	0xc1, 0xdc, 0x5d, 0xde, 0xc8, 0xdb, 0x65, 0xcf, 0xd9, 0x65, 0x83, 0xd4, 0xc3, 0x50, 0xb7, 0x9b,
	0x01, 0x90, 0x6a, 0xa9, 0x65, 0x64, 0x6b, 0x2b, 0x9a, 0xeb, 0xa0, 0x44, 0x84, 0x66, 0xa6, 0xff,
	0x11, 0x6c, 0xb7, 0xd5, 0xc5, 0xcd, 0xcd, 0x28, 0x4e, 0x30, 0x78, 0x46, 0xb1, 0xb9, 0x83, 0xbd,
	0x82, 0x92, 0xe5, 0x49, 0x0a, 0xfa, 0x2f, 0x01, 0xe6, 0xd6, 0x23, 0x42, 0x3b, 0x51, 0x56, 0x87,
	0xc0, 0x51, 0xfb, 0x2c, 0xd1, 0x28, 0x69, 0x17, 0x8d, 0x7a, 0x2f, 0xa0, 0x48, 0x5e, 0xaa, 0xb7,
	0x54, 0xfb, 0xc0, 0x42, 0x64, 0x82, 0x70, 0x1b, 0x65, 0x75, 0x38, 0x74, 0x20, 0x54, 0x3b, 0xc9,
	0x00, 0x3e, 0x87, 0x4d, 0xeb, 0x0b, 0x3c, 0x22, 0xb1, 0x84, 0x90, 0x86, 0x1f, 0xf4, 0xfc, 0xec,
	0xcf, 0x58, 0x67, 0x18, 0x79, 0x3d, 0xff, 0x6b, 0x63, 0x81, 0x39, 0x47, 0xe7, 0xa5, 0x30, 0x72,
	0x75, 0x27, 0x23, 0x1d, 0xdf, 0x8d, 0x50, 0xd1, 0xb9, 0x22, 0x9f, 0x3b, 0xfc, 0x2a, 0x6c, 0x77,
	0x84, 0x8c, 0xf2, 0x76, 0x61, 0x1e, 0xf4, 0x4f, 0x61, 0x37, 0x2d, 0x2a, 0xc2, 0x44, 0xc7, 0x7a,
	0x1a, 0x40, 0xc5, 0xab, 0xee, 0xd6, 0x76, 0x6d, 0xfa, 0xcc, 0xcb, 0x1f, 0x64, 0xf9, 0x5f, 0x01,
	0x34, 0x51, 0x0d, 0x95, 0xbd, 0xa2, 0x44, 0x57, 0x94, 0x9d, 0xe2, 0xc9, 0xcf, 0x9d, 0x1c, 0xff,
	0x14, 0x0e, 0x97, 0x5f, 0x29, 0x1d, 0x6a, 0xd3, 0x6d, 0xaf, 0xba, 0xc5, 0x73, 0xa2, 0xec, 0x9f,
	0x02, 0xec, 0xcf, 0x65, 0xa0, 0xff, 0x01, 0x52, 0x80, 0xc1, 0x33, 0xcb, 0x29, 0x13, 0xcf, 0xab,
	0x7a, 0x7c, 0xc1, 0xe7, 0xbf, 0x84, 0xb2, 0xb5, 0x89, 0x42, 0x83, 0xbe, 0x0e, 0x4c, 0xa3, 0x8a,
	0x7c, 0xc9, 0xef, 0xd7, 0xa0, 0xe4, 0xf8, 0x52, 0xd5, 0x96, 0x4b, 0x72, 0x93, 0xd8, 0x2b, 0xf8,
	0xd8, 0x52, 0xab, 0x4f, 0xf4, 0xad, 0x90, 0xb1, 0x9e, 0xba, 0xfc, 0x57, 0x76, 0xf7, 0x02, 0x3e,
	0x7c, 0x70, 0xf4, 0x49, 0x2f, 0x1c, 0x2d, 0xd0, 0x77, 0xb1, 0x54, 0x3a, 0xdd, 0xe8, 0x99, 0xc9,
	0x4e, 0x67, 0x43, 0xda, 0x43, 0x9d, 0x4d, 0xc2, 0xdb, 0x67, 0x85, 0xfd, 0x3c, 0x7b, 0x5a, 0x7a,
	0xa8, 0x9f, 0xc2, 0xfc, 0xe9, 0xc3, 0xc5, 0xfe, 0x2e, 0x80, 0x3f, 0x6f, 0x9d, 0xf8, 0x03, 0x25,
	0x01, 0x7f, 0x06, 0x9b, 0x3f, 0xc5, 0x49, 0x92, 0xae, 0xdd, 0xf2, 0xac, 0xa5, 0x51, 0xff, 0x0b,
	0xd8, 0x7b, 0x1d, 0x2a, 0xbc, 0x14, 0x71, 0xa2, 0x2f, 0x51, 0xd2, 0xbf, 0x7f, 0xfa, 0x6d, 0xb3,
	0x1c, 0x58, 0xac, 0xd2, 0x7b, 0x58, 0x65, 0x6d, 0x61, 0x97, 0xe8, 0x91, 0xea, 0xa0, 0x52, 0xab,
	0x0a, 0xbd, 0xde, 0xa4, 0x2f, 0xe4, 0x6f, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x6c, 0xe0,
	0x89, 0x53, 0x0b, 0x00, 0x00,
}
